server:
  port: 8001

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    use-column-label: true
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: wenbingkun-springcloud
  company.name: wenbingkun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$